### ISSUE TITLE
gnome shell 3.14 has some issue.

### ISSUE THREAD

**Issue by whdgmawkd** [daniruiz/Super-Flat-Remix-GNOME-theme#1]
.popup-menu css has no text colored...
only can see system icon tray popup.
and cant see calender, openweather(extension),systemmonitor(extension).
plz add ".popup-menu * { color:#??????;}"or any trick.

**Comment by JamesLiAndroid** [comment]
Is it support jessie？

**Comment by whdgmawkd** [comment]
@JamesLiAndroid this issue found on debian 8, so theme supports debian. but has some issue.
