### ISSUE TITLE
top bar text (system tray, calendar, all that stuff) very light

### ISSUE THREAD

**Issue by 2394y234y23894y2389** [daniruiz/Super-Flat-Remix-GNOME-theme#7]
System tray icons (in the dropdown menu, no problem with top bar icons) also very light.

I think it's lighter than it's supposed to be. I remember using this theme in the past and having it be better. Was there a change recently that made this stuff lighter? It wasn't a good move if so imo. 

All other text is fine, it's just the stuff from drop down menus from the top bar, including from extensions like openweather.

I have Gnome shell 3.16.1

**Comment by dwlsalmeida** [comment]
Did you figure out a way to fix it? I'm currently going through the css trying to find where this is coded in
